# Generated by Django 6.1.1 on 2026-09-24 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rating_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
